@Webhooks.Api.http_HostAddress = http://localhost:5041

GET {{Webhooks.Api.http_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Webhooks.Api.http_HostAddress}}/orders
Content-Type:application/json

{
  "customerName":"string",
  "amount":123
}

###

POST {{Webhooks.Api.http_HostAddress}}/webhooks/subscription
Content-Type:application/json

{
  "eventType":"order.created",
  "webhookUrl":"https://webhook.site/5e6b55ed-d4ba-4743-b61b-8f4b4831279a"
}


###

POST {{Webhooks.Api.http_HostAddress}}/orders
Content-Type:application/json

{
   "customerName":"string",
  "amount":123
}